### ISSUE TITLE
Current problems & TODO's

### ISSUE THREAD

**Issue by sum01** [sum01/vcash#3]
# TODO
- [ ] Test on Ubuntu, Windows 10, and macOS.

# Bugs
- [x] Fix compatibility with systems that have a newer OpenSSL installed. 
```
vcash/coin/include/coin/big_number.hpp:40:31: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
     class big_number : public BIGNUM
```
Update 1: It seems that build flags and the pre-existing FindOpenSSL might be the best route. I've found..
```
-DOPENSSL_ROOT_DIR="/usr/include/openssl-1.0" -DOPENSSL_USE_STATIC_LIBS=TRUE -DCMAKE_FIND_LIBRARY_SUFFIXES=".so.1.0.0"
```
flags to almost work, but it fails to find OPENSSL_CRYPTO_LIBRARY. Needs more digging into the module...
Update 2: It seems that `find_library(OPENSSL_CRYPTO_LIBRARY)` looks for `crypto` instead of `libcrypto` in the NAMES. Unsure if a lib prefix gets added, or if that's the actual issue...

# Done/Fixed
- [x] Fix the boost::noncopyable error.
In commit 6f6c10b18afc54455f304f7db3c2c706274fef2a
- [x] ~Test with GCC v6 or higher once build is in better shape.~ Add GCC flags.
In commit 3a34878d4001952b3a612d56432b4e6e0f40f9d8
- [x] Fix various deprecated warnings.
Fixed in upstream https://github.com/openvcash/vcash/commit/d1f0ae26de80c7de0f17fb8c81d0dd48eff51640 merged with 1536222b7d046e15e9f7aa2379a1524ac5056727 and 3bdbc3585a1a3bafb8a6b216338d574e5c57b679
- [x] Implement Windows into [CMake module](https://github.com/sum01/vcash/blob/add-cmake-and-cleanup/cmake/Modules/FindBerkeleyDB.cmake)
Partially (all?) done in 6709dbca2e14b5eeed80533f2ba44fc14f2f9b20
